modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/DenimsMods/Grapevine/issues"
license = "LGPLv3"

[[mods]]
modId = "grapevine"
version = "${version}"
displayName = "Grapevine"
authors = "DenimRed"
description = "Adds chat channels, including proximity chat"
#logoFile = "grapevine.png"

[[dependencies.grapevine]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grapevine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grapevine]]
modId = "architectury"
mandatory = true
versionRange = "[4.8.79,)"
ordering = "AFTER"
side = "BOTH"